# Generated by Django 5.1 on 2024-08-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("brand", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("mileage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("seating_capacity", models.IntegerField()),
                ("image_url", models.URLField()),
                ("car", models.CharField(max_length=100)),
                ("transmission", models.CharField(max_length=50)),
                ("fuel_type", models.CharField(max_length=50)),
            ],
        ),
    ]
